<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="1" ignored="0" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Smoke" duration-ms="48744" started-at="2020-03-29T23:20:48 IST" finished-at="2020-03-29T23:21:37 IST">
    <groups>
    </groups>
    <test name="Smoke" duration-ms="48744" started-at="2020-03-29T23:20:48 IST" finished-at="2020-03-29T23:21:37 IST">
      <class name="com.project.Testcases.NavigateAndLoginToSauceDemo">
        <test-method status="PASS" signature="onStart()[pri:0, instance:com.project.Testcases.NavigateAndLoginToSauceDemo@74294adb]" name="onStart" is-config="true" duration-ms="679" started-at="2020-03-29T23:20:48 IST" finished-at="2020-03-29T23:20:48 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- onStart -->
        <test-method status="PASS" signature="pageObjects()[pri:0, instance:com.project.Testcases.NavigateAndLoginToSauceDemo@74294adb]" name="pageObjects" is-config="true" duration-ms="9" started-at="2020-03-29T23:20:49 IST" finished-at="2020-03-29T23:20:49 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- pageObjects -->
        <test-method status="FAIL" signature="navigateToSauceDemo()[pri:0, instance:com.project.Testcases.NavigateAndLoginToSauceDemo@74294adb]" name="navigateToSauceDemo" duration-ms="48292" started-at="2020-03-29T23:20:49 IST" description="Navigate to the given test site and asserting it&#039;s title" finished-at="2020-03-29T23:21:37 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unable to visit website due to exception: org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(C:\Program Files\Mozilla Firefox\firefox.exe) on port 7055; process output follows: 

Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'apanigrahi-pc', ip: '172.18.238.214', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_241'
Driver info: driver.version: FirefoxDriver]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unable to visit website due to exception: org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(C:\Program Files\Mozilla Firefox\firefox.exe) on port 7055; process output follows: 

Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'apanigrahi-pc', ip: '172.18.238.214', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_241'
Driver info: driver.version: FirefoxDriver
at org.testng.Assert.fail(Assert.java:97)
at com.project.Utility.BrowserFactory.navigateToTestSite(BrowserFactory.java:70)
at com.project.Testcases.NavigateAndLoginToSauceDemo.navigateToSauceDemo(NavigateAndLoginToSauceDemo.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigateToSauceDemo -->
        <test-method status="SKIP" signature="loginToSauceDemo(java.lang.String, java.lang.String)[pri:0, instance:com.project.Testcases.NavigateAndLoginToSauceDemo@74294adb]" name="loginToSauceDemo" duration-ms="0" started-at="2020-03-29T23:21:37 IST" description="Logging in to given test site and asserting it&#039;s title" depends-on-methods="com.project.Testcases.NavigateAndLoginToSauceDemo.navigateToSauceDemo" finished-at="2020-03-29T23:21:37 IST">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method NavigateAndLoginToSauceDemo.loginToSauceDemo(java.lang.String, java.lang.String)[pri:0, instance:com.project.Testcases.NavigateAndLoginToSauceDemo@74294adb] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method NavigateAndLoginToSauceDemo.loginToSauceDemo(java.lang.String, java.lang.String)[pri:0, instance:com.project.Testcases.NavigateAndLoginToSauceDemo@74294adb] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:101)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToSauceDemo -->
        <test-method status="SKIP" signature="logoutOfSauceDemo()[pri:0, instance:com.project.Testcases.NavigateAndLoginToSauceDemo@74294adb]" name="logoutOfSauceDemo" duration-ms="0" started-at="2020-03-29T23:21:37 IST" description="Logging out of given test site and asserting it&#039;s title" depends-on-methods="com.project.Testcases.NavigateAndLoginToSauceDemo.loginToSauceDemo" finished-at="2020-03-29T23:21:37 IST">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method NavigateAndLoginToSauceDemo.logoutOfSauceDemo()[pri:0, instance:com.project.Testcases.NavigateAndLoginToSauceDemo@74294adb] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method NavigateAndLoginToSauceDemo.logoutOfSauceDemo()[pri:0, instance:com.project.Testcases.NavigateAndLoginToSauceDemo@74294adb] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:101)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutOfSauceDemo -->
        <test-method status="PASS" signature="finishedTest()[pri:0, instance:com.project.Testcases.NavigateAndLoginToSauceDemo@74294adb]" name="finishedTest" is-config="true" duration-ms="0" started-at="2020-03-29T23:21:37 IST" finished-at="2020-03-29T23:21:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- finishedTest -->
      </class> <!-- com.project.Testcases.NavigateAndLoginToSauceDemo -->
    </test> <!-- Smoke -->
  </suite> <!-- Smoke -->
</testng-results>
